[package]
name = "rocket-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# https://api.rocket.rs/v0.5-rc/rocket/

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["secrets", "json"] }
